/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.vincenzopalazzo.lightning;

import io.vincenzopalazzo.lightning.rest.CLightningRestPlugin;

public class App {

  public static void main(String[] args) throws Exception {
    CLightningRestPlugin restPlugin = new CLightningRestPlugin();
    restPlugin.start();
  }
}
